### PR TITLE
rename traversable to iterable

### PR DESCRIPTION
**Pull request by i10416**
fix https://github.com/typelevel/spire/issues/777

### CODE REVIEW

**Review by armanbilge — APPROVED** [review]
Thanks, LGTM!

My only question is, does this completely close #777? Is `Traversable` used anywhere else in spire?

**Comment by i10416** [comment]
As of spire, `Traversable`s are dropped by https://github.com/typelevel/spire/commit/3446d41fbbf3c0a117b4b5c86fe0ec2e7d539fd5 and  https://github.com/typelevel/spire/commit/1e6fa56255d7812f78dbce280b6ddde911884b59

**Comment by i10416** [comment]
Algebra seems to drop Traversable, but there remains some, I sent PR https://github.com/typelevel/algebra/pull/252.

**Comment by i10416** [comment]
Anyway, in spire side, all traversable has already been replaced with Iterable, thus I think #777 can be closed.

**Comment by armanbilge** [comment]
Thanks for looking into that!

**Comment by i10416** [comment]
You're welcome. Thanks for reviewing!

**Pull request merged**
