### PR TITLE
Bump Scala and Scala.js versions, bump algebra, cross publish SJS 0.6, drop 2.11 support

### PR DESCRIPTION
**Pull request by denisrosset**

### CODE REVIEW

**Comment by cquiroz** [comment]
Thanks for this. Please note that scala.js 1.1.0 is already available

**Comment by erikerlandson** [comment]
looks like scalac-scoverage-runtime isn't building for scalaJS 1.x
```
Error downloading org.scoverage:scalac-scoverage-runtime_sjs1.0_2.12:1.4.1
```

**Comment by erikerlandson** [comment]
xref:  https://github.com/scoverage/scalac-scoverage-plugin/pull/289

**Comment by larsrh** [comment]
Maybe we can remove coverage for the time being?

**Comment by erikerlandson** [comment]
Is the plan to turn off coverage for JS 1.x for now?

**Comment by larsrh** [comment]
Yes. Help would be much appreciated.

**Comment by erikerlandson** [comment]
I can do a PR for it if that is helpful.  I had been assuming Dennis was just going to tweak this one to disable the coverage.

**Pull request merged**
