### PR TITLE
New spire.stats package (take 2)

### PR DESCRIPTION
**Pull request by andrelfpinto**
Hello again,
This is a second attempt to an alternate proposal for the random package as seen in #214. For more information about the first one (to avoid redundancy) refer to #460. The only difference is that this one complies with the restructuring that took place to add scala-js support.
I'm sorry that I cannot give continuous contributions to the project.
As always, feel free to suggest modifications and improvements.

### CODE REVIEW

**Comment by denisrosset** [comment]
Grouped in its own issue. This should probably go in a separate module, maybe with the spire.random subpackage.
@andrelfpinto Are you interested moving this forward and reopen this PR?

**Comment by andrelfpinto** [comment]
I will try to. Maybe I will need some help.

**Comment by denisrosset** [comment]
Are you at nescala btw? If you do anything, please base your PR on the modularization PR, and put stuff in a separate module such as spire-stats or spire-random. We hope to get this big changes done as soon as possible, but we may hit roadblocks.

**Comment by larsrh** [comment]
Closing this because it hasn't seen activity in over a year.

**Pull request closed without merging**
