### PR TITLE
Jetdim compile time check

### PR DESCRIPTION
**Pull request by non**
This is a port of https://github.com/non/spire/pull/438 which includes an extra commit.

I'd be happy to merge this and then consider the fate of `NonZero`, `NonNegative`, etc.

What do you all think?

### CODE REVIEW

**Comment by non** [comment]
Thanks @kevinmeredith! Good catch. I'll make the constructor `private[spire]`.

**Comment by kevinmeredith** [comment]
Is it worthwhile to just use `Nat` from shapeless? If it's like Idris's `Nat`, then it starts at 0.

However, is there a way to use shapeless Nat's to fail to compile (like this PR's `PositiveInt`) if it equals `Z`, i.e. only compile if it's a `successor`?

**Comment by denisrosset** [comment]
Hi @non, we discussed last year to move `Jet` towards legacy as it is currently not well-defined (is it an associative algebra element? or an automatic differentiation type that pretends to be whatever the underlying scalar is?)

As such, I'd be keen on closing this PR. What do you think?

**Comment by larsrh** [comment]
Closing this because it hasn't seen activity in over a year.

**Pull request closed without merging**
