### PR TITLE
Use new SBT syntax in CI pipeline

### PR DESCRIPTION
**Pull request by danicheg**
A tiny cleanup.

### CODE REVIEW

**Comment by armanbilge** [comment]
Thanks! We're holding all PRs for the moment while @cquiroz works on the Scala 3 cross-build.

**Comment by cquiroz** [comment]
In `spire` workflows are generated via `sbt-guthub-actions` thus we can't really edit the yml files by hand. Thats why this PR failed in CI

**Comment by danicheg** [comment]
@cquiroz oops, that is true. It's needed to fix that in `build.sbt` though.

**Comment by danicheg** [comment]
@cquiroz @armanbilge done!

**Review by cquiroz — APPROVED** [review]
Thanks, this looks good. We could merge this without affecting the scala3 work

**Review by armanbilge — APPROVED** [review]

**Pull request merged**
